version: "3.9"
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: piazza
    networks:
      - user_netw
    volumes:
      - ../../libs/postgres/src/main/resources/db.migration/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../../libs/postgres/src/main/resources/db.migration/V1__1.0__CreateUserTable.sql:/docker-entrypoint-initdb.d/V1__1.0__CreateUserTable.sql
  user-app:
    container_name: user-app
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:9096
    build:
      context: "../../"
      dockerfile: "apps/user-app/Dockerfile"
    depends_on:
      - postgres
    networks:
      - kafka_docker_network
      - user_netw
    ports:
      - "8081:8081"
networks:
  kafka_docker_network:
    external: true
  user_netw:
    name: user_network