server:
  port : 8083
spring :
  kafka :
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      acks: 1
    consumer :
      enable-auto-commit : false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted:
              packages: '*'

kafka:
  topics:
    course:
      name: notification.topic
      partitions: 6
      replicas: 1
  consumer:
    id: notification.app
    group-id: notification.group
    concurrency: 6