version: "3.9"
services:
  arangodb:
    image: arangodb:latest
    environment:
      ARANGO_NO_AUTH: 1
    ports:
      - "8529:8529"
    networks:
      - course_nw
    volumes:
      - arangodb_data_container:/var/lib/arangodb3
      - arangodb_apps_data_container:/var/lib/arangodb3-apps
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    volumes:
      - ./storage/minio:/data
    environment:
      MINIO_ACCESS_KEY: hyVNqge8gFUELj0t
      MINIO_SECRET_KEY: nfOGaowmOy6w61tUPQ3b760bog19C9Di
    command: server /data
    networks:
      - course_nw
  course-app:
    build:
      context: "../../"
      dockerfile: "apps/course-app/Dockerfile"
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:9095
    ports:
      - "8082:8082"
    networks:
      - kafka_docker_network
      - course_nw

volumes:
  arangodb_data_container:
  arangodb_apps_data_container:

networks:
  course_nw:
    name: course_nw
  kafka_docker_network:
    external: true